### ISSUE TITLE
Log Explore: Patterns always loading

### ISSUE THREAD

**Issue by yincongcyincong** [grafana/explore-logs#1005]
### What happened?

when there is no pattern to show, the Patterns always loading.
https://github.com/user-attachments/assets/39e3d571-7805-41bb-a567-74a9ce5a5eff

### What did you expect to happen?

show nothing when there is no pattern to show. don't still loading

### Did this work before?

i don't know

### How do we reproduce it?

1. go to logs explore
2. go to log detail 
3. click pattern

### Environment (with versions)?

Grafana: 11.4.0
OS: macos
Browser: chrome

### Grafana platform?

None

**Comment by gtk-grafana** [comment]
@yincongcyincong I'm not able to reproduce what you are seeing for labels that do not have patterns:

<img width="1728" alt="Image" src="https://github.com/user-attachments/assets/38c37178-e62f-4324-8e68-d73ec2e28bfc" />

Have you configured your Loki instance to work with patterns? 
https://github.com/grafana/explore-logs?tab=readme-ov-file#installation-in-your-own-grafana-instance

If you can provide a HAR file containing the patterns network request that would be very helpful in tracking down the issue you are seeing.

Additionally what version of Grafana, Explore Logs, and Loki are you running?

**Comment by yincongcyincong** [comment]
grafana: main branch
loki: main branch

grafana request `
http://localhost:3000/grafana/api/datasources/uid/be9cx5z4ev01sf/resources/patterns?query=%7Bservice_name%3D%60varlogs-loki%60%7D&start=2025-01-22T00%3A31%3A22.338Z&end=2025-01-22T06%3A31%3A22.338Z&step=30s`

just get response like this: 
![Image](https://github.com/user-attachments/assets/f98ef8e8-5b60-4dc3-8a49-20f85b9d54ba)

**Comment by gtk-grafana** [comment]
@yincongcyincong can you share your `loki-config.yaml`?

Does it contain?
```
pattern_ingester:
  enabled: true
```

**Comment by yincongcyincong** [comment]
@gtk-grafana 
```
auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096
  http_listen_address: 127.0.0.1
  grpc_listen_address: 127.0.0.1

common:
  instance_addr: 127.0.0.1
  path_prefix: /tmp/loki
  storage:
    filesystem:
      chunks_directory: /tmp/loki/chunks
      rules_directory: /tmp/loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

schema_config:
  configs:
    - from: 2020-10-24
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

ruler:
  alertmanager_url: http://localhost:9093

frontend:
  encoding: protobuf

# By default, Loki will send anonymous, but uniquely-identifiable usage and configuration
# analytics to Grafana Labs. These statistics are sent to https://stats.grafana.org/
#
# Statistics help us better understand how Loki is used, and they show us performance
# levels for most users. This helps us prioritize features and documentation.
# For more information on what's sent, look at
# https://github.com/grafana/loki/blob/main/pkg/analytics/stats.go
# Refer to the buildReport method to see what goes into a report.
#
# If you would like to disable reporting, uncomment the following lines:
#analytics:
#  reporting_enabled: false
```
