### ISSUE TITLE
I tried installing the plugin on my grafana in k8s and I get a 404 when accessing the page

### ISSUE THREAD

**Issue by batazor** [grafana/explore-logs#219]
grafana: **11.0.0-preview**
loki: **3.0.0**

<img width="1492" alt="Screenshot 2024-04-11 at 00 24 46" src="https://github.com/grafana/explore-logs/assets/1643797/593f589a-6cea-41e0-91f9-db6bcd35772f">
<img width="856" alt="Screenshot 2024-04-11 at 00 25 31" src="https://github.com/grafana/explore-logs/assets/1643797/6b344761-be18-406c-b3ae-7ccbe0f5ef34">

<img width="451" alt="Screenshot 2024-04-11 at 00 28 00" src="https://github.com/grafana/explore-logs/assets/1643797/98a37ea2-560d-49d9-9f36-fe959cb7fbc1">

---

Is anything else required?

**Comment by daudcanugerah** [comment]
Mee tooo

**Comment by svennergr** [comment]
@batazor @daudcanugerah  Do you have this `limits_config` `volume_enabled` enabled?

https://github.com/grafana/explore-logs/blob/main/config/loki-config.yaml#L26

**Comment by batazor** [comment]
@svennergr no, my config:

```
limits_config:
      max_cache_freshness_per_query: 10m
      query_timeout: 300s
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      split_queries_by_interval: 15m
```
