### ISSUE TITLE
Loki Grafana - Explore Logs Plugin

### ISSUE THREAD

**Issue by MuhammadJamee** [grafana/explore-logs#816]
Hello everyone,

I have trying to work with explore logs plugin. I have installed plugin and set configs according to the guide. However, the results are not as expected. 

Config file

```
auth_enabled: false

server:
  http_listen_port: 3333
  grpc_listen_port: 9999
  grpc_server_max_concurrent_streams: 1000
  grpc_server_max_recv_msg_size: 100000000
  grpc_server_max_send_msg_size: 100000000

common:
  instance_addr: 127.0.0.1
  path_prefix: E:\GrafanaLogging\Installation\loki
  storage:
    filesystem:
      chunks_directory: E:\GrafanaLogging\Installation\loki\chunks
      rules_directory: E:\GrafanaLogging\Installation\loki\rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

pattern_ingester:
  enabled: true

query_range:
  parallelise_shardable_queries: true
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 20480

schema_config:
  configs:
    - from: 2024-10-06
      store: tsdb          # Change this to `tsdb` for structured metadata
      object_store: filesystem
      schema: v13          # Update schema to v13
      index:
        prefix: index_
        period: 24h

ruler:
  alertmanager_url: http://localhost:9093

query_scheduler:
  max_outstanding_requests_per_tenant: 16384
  
ingester:
  max_chunk_age: 1h
  chunk_target_size: 1048576

compactor:
  working_directory: E:\GrafanaLogging\Installation\loki\compactor
  retention_enabled: true
  retention_delete_delay: 1h
  retention_delete_worker_count: 500
  delete_request_cancel_period: 5m
  delete_request_store: filesystem  # Add this line

limits_config:
  ingestion_rate_mb: 20
  ingestion_burst_size_mb: 40
  max_streams_per_user: 50000
  retention_period: 7d
  volume_enabled: true
  split_queries_by_interval: 15m
  allow_structured_metadata: false  # Disable structured metadata temporarily

analytics:
  reporting_enabled: false

```
Versions

Loki: 3.2 +
Grafan: 11 +

**Output on the screen: http://localhost/a/grafana-lokiexplore-app**

```



Log volume has not been configured.

[Instructions to enable volume in the Loki config:](https://grafana.com/docs/loki/latest/reference/api/#query-log-volume)

limits_config:
  volume_enabled: true



```
