### ISSUE TITLE
Log volume has not been configured

### ISSUE THREAD

**Issue by MatteoGioioso** [grafana/explore-logs#897]
Hello,

I am trying to run loki with promtail and grafana loki explorer plug-in, however it does not seem to work.

![Image](https://github.com/user-attachments/assets/e9b68499-46d3-4588-8598-2ba6d77678b1)

With the following error in console:

```
runRequest.ts:167 runRequest.catchError TypeError: Cannot read properties of undefined (reading '$variables')
    at ae (lookupVariable.js:2:39)
    at eval (sceneInterpolator.js:38:20)
    at eval (sceneInterpolator.js:17:22)
    at String.replace (<anonymous>)
    at ct (sceneInterpolator.js:14:17)
    at Object._l [as interpolate] (sceneGraph.js:31:10)
    at wb (scenes.ts:17:21)
    at p.eval [as _subscribe] (datasource.ts:89:14)
    at p._trySubscribe (Observable.js:38:25)
    at Observable.js:32:31
```

It tells me that log volume has not been configured, but it has been, unless I am missing something. 
No error logs in Loki, it seems it is ingesting logs:

```
loki          | level=info ts=2024-11-18T11:06:24.642244039Z caller=flush.go:196 component=ingester msg="flushing stream" user=fake fp=2dea25fab47363b6 immediate=false num_chunks=3 labels="{__stream_shard__=\"2\", filename=\"/logs/postgres/postgresql-1.csv\", job=\"postgres_one-postgres\", service_name=\"postgres_one-postgres\"}"
loki          | level=info ts=2024-11-18T11:06:24.644114148Z caller=flush.go:196 component=ingester msg="flushing stream" user=fake fp=ce3eae7f2729cb6b immediate=false num_chunks=5 labels="{__stream_shard__=\"1\", filename=\"/logs/postgres/postgresql-1.csv\", job=\"postgres_one-postgres\", service_name=\"postgres_one-postgres\"}"
loki          | level=info ts=2024-11-18T11:06:24.646218318Z caller=flush.go:196 component=ingester msg="flushing stream" user=fake fp=dd428830992d1815 immediate=false num_chunks=5 labels="{__stream_shard__=\"0\", filename=\"/logs/postgres/postgresql-1.csv\", job=\"postgres_one-postgres\", service_name=\"postgres_one-postgres\"}"
```

Versions:

```
Loki: 3.0.2 (latest)
Grafana: 11.0.3
Loki explorer plugin: 1.0.1
Promtail: 3.2.1
```

Loki config:

```
auth_enabled: false

limits_config:
  allow_structured_metadata: true
  volume_enabled: true
  ingestion_rate_mb: 10240
  ingestion_burst_size_mb: 10240

server:
  http_listen_port: 3100
  grpc_server_max_recv_msg_size: 104857600 # 100 MB, might be too much, be careful
  grpc_server_max_send_msg_size: 104857600 # 100 MB, might be too much, be careful

common:
  ring:
    instance_addr: 0.0.0.0
    kvstore:
      store: inmemory
  replication_factor: 1
  path_prefix: /tmp/loki

schema_config:
  configs:
    - from: 2020-05-15
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  tsdb_shipper:
    active_index_directory: /tmp/loki/index
    cache_location: /tmp/loki/index_cache
  filesystem:
    directory: /tmp/loki/chunks

pattern_ingester:
  enabled: true

analytics:
  reporting_enabled: false

```

Log explorer plugin config:

```
apiVersion: 1

apps:
  - type: grafana-lokiexplore-app
    disabled: false
    jsonData:
      apiUrl: http://default-url.com
      isApiKeySet: true
    secureJsonData:
      apiKey: secret-key

```

and installed via:  `'https://storage.googleapis.com/integration-artifacts/grafana-lokiexplore-app/grafana-lokiexplore-app-1.0.1.zip;grafana-lokiexplore-app,'`

Grafana config:

```
[paths]
# Directory where grafana will automatically scan and look for plugins
plugins = /var/lib/grafana/plugins
provisioning = /etc/grafana/provisioning
data = /borealis/db

#################################### Server ####################################
[server]
# enable gzip
enable_gzip = true

serve_from_sub_path = false

#################################### Dashboards History ##################
[dashboards]
# Path to the default home dashboard. If this value is empty, then Grafana uses StaticRootPath + "dashboards/home.json"
default_home_dashboard_path = /var/lib/grafana/dashboards/Home/borealis-home.json

#################################### Users ###############################
[users]
default_theme = light
# Path to a custom home page. Users are only redirected to this if the default home dashboard is used. It should match a frontend route and contain a leading slash.
allow_sign_up = false

#################################### Auth ######################
[auth.anonymous]
# enable anonymous access
enabled = true
org_role = Admin
```
